### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by burrly** [nittanygeek/LiDAR-Importer#3]
Hey, getting an error when I try to install the plugin on Blender 2.79 or 2.82

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Neilson\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\__init___.py", line 25, in <module>
    from . import auto_load
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by roninio** [comment]
I had the same error just remove 
`auto_load`
From all places in the code. I managed to load and view

**Comment by nittanygeek** [comment]
Should be cleaned up now.  Sorry about that.
