### ISSUE TITLE
Incompatible with latest laspy version

### ISSUE THREAD

**Issue by jurajpalenik** [nittanygeek/LiDAR-Importer#6]
Hey,

I've just installed the add-on, however I had to edit the line 39 to: 

`
`

**Comment by degreal** [comment]
I have no luck with this method. I dont understand. How can it install laspy and not find it at the same time?
```
Successfully installed laspy-1.7.1
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Allan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\__init___.py", line 41, in <module>
    import laspy
ModuleNotFoundError: No module named 'laspy'
```

**Comment by degreal** [comment]
I have no luck with this mthod. It succesfully installs laspy and not find it at the same time

```
Successfully installed laspy-1.7.1
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Degreal\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\__init___.py", line 41, in <module>
    import laspy
ModuleNotFoundError: No module named 'laspy'
```

**Comment by MariaMel98** [comment]
> 

I'm trying this but it doesn't work. I tried manually to install laspy < 2 but i got an error which i think is because I'm using python 3.10 and maybe it is incompatible with such old  laspy version. Could you tell me what version of python and blender are you using?

**Comment by jurajpalenik** [comment]
Hi! I am afraid I don't remember which version of python and blender I used last year, but I've just tried to install 
`pip install laspy<2.0` into a brand new virtual environment using python 3.10.2 and it successfully installed laspy-1.7.1. What error did you get?

**Comment by MariaMel98** [comment]
Turns out it was an error of the specific version (1.7.1) I was trying to install. I tried version 1.7.0 and it worked! But now when i import the las file all I see is one dot in the center...I'm thinking that this happens because of the known issue "The points are not centered after importing, so you will need to scale the object after importing before the verticies are visible in Blender's viewport."

**Comment by Willem3141** [comment]
FWIW, I couldn't get laspy-1.7.1 to install so instead I fixed this addon to make it work with laspy-2.0. I made a PR here: https://github.com/nittanygeek/LiDAR-Importer/pull/11

**Comment by nittanygeek** [comment]
Closing issue as I have merged the PR.  Thanks @Willem3141!
